### ISSUE TITLE
MAP_POINTER_MOVED Event Consumes All Events for Map and Markers

### ISSUE THREAD

**Issue by RbtsEvrwhr-Riley** [sothawo/mapjfx#97] opened 2021-03-09 18:50 UTC
This is reproducible using the demo app and the logger included. Logging should be on debug.

Just move the mouse around the map, and try to click on markers, right click / click map, etc, to generate logging events. None are generated other than the moved pointer.

Cannot currently find workaround. Trying to implement a basic move waypoint control using a context menu, since drag-drop is not supported by this webview implementation.

This is pretty close to minimal repro, adding and deleting configs from the map does not change anything.

Java 11, javafx 11.0.2, mapjfx 2.15.2.

**Comment by sothawo** [comment] 2021-03-09 19:59
I cannot reproduce this. In both applications - the `TestApp` that is contained in this repository, and the demo application from https://github.com/sothawo/mapjfx-demo - I get events when clicking on a marker or a label, for both left and right mouse clicks.

What OS are you running? Windows/Mac/Linux?

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-09 20:04
Huh, I had Windows 10 listed in the ticket, I wonder where it went?

Very strange. So you get events, including move events, whereas in both the demo and my application, whenever a MAP_POINTER_MOVED is set, it is the only event thrown. Let's see if we can find a root cause here...

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-09 20:18
An interesting log snippet. When I build, it logs the following despite the classpath only having java 11 libs, and nowhere I can find even having ACCESS to 15. It appears it's somehow inheriting a different Java version?

I'll do a new pull and try with TestApp. Also, are there any known issues with 15? This could be related.

15:13:47.405 [JavaFX Application Thread] INFO com.sothawo.mapjfxdemo.DemoApp - starting DemoApp
15:13:47.408 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.DemoApp - loading fxml file /fxml/DemoApp.fxml
15:13:47.688 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.Controller - map type toggled to RadioButton[id=radioMsOSM, styleClass=radio-button]'OSM'
15:13:47.722 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - initializing...
15:13:47.726 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - Configuration{projection=WEB_MERCATOR, interactive=true, showZoomControls=false}
15:13:47.727 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - loading from jar:file:///C:/Users/USER/.m2/repository/com/sothawo/mapjfx/2.15.2/mapjfx-2.15.2.jar!/mapview.html
15:13:48.135 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - Java Version:   15.0.1+9-18
15:13:48.135 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - JavaFX Version: 15.0.1+1
15:13:48.135 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - OS:             Windows 10, 10.0, amd64
15:13:48.136 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - User Agent:     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/610.1 (KHTML, like Gecko) JavaFX/15 Safari/610.1
15:13:48.136 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - load html into WebEngine
15:13:48.171 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.Controller - initialization finished
15:13:48.662 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.DemoApp - application start method finished.
15:13:49.161 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - calling JS "createJSMapView('{"projection":"EPSG:3857","interactive":true,"showZoomControls":false}')"
15:13:49.166 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView$JavaConnector - JS Console: {"projection":"EPSG:3857","interactive":true,"showZoomControls":false}
15:13:49.188 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - setting map type in OpenLayers map: OSM

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-09 20:37
Okay. While what I found is an interesting issue, it is with javaFX and not mapjfx, and also does not affect the current issue.

15:36:04.535 [JavaFX Application Thread] INFO com.sothawo.mapjfxdemo.DemoApp - starting DemoApp
15:36:04.539 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.DemoApp - loading fxml file /fxml/DemoApp.fxml
15:36:04.849 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.Controller - map type toggled to RadioButton[id=radioMsOSM, styleClass=radio-button]'OSM'
15:36:04.881 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - initializing...
15:36:04.890 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - Configuration{projection=WEB_MERCATOR, interactive=true, showZoomControls=false}
15:36:04.890 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - loading from jar:file:///C:/Users/cs_ri/.m2/repository/com/sothawo/mapjfx/2.15.2/mapjfx-2.15.2.jar!/mapview.html
15:36:05.145 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - Java Version:   11.0.10+9
15:36:05.145 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - JavaFX Version: 11.0.2+1
15:36:05.145 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - OS:             Windows 10, 10.0, amd64
15:36:05.145 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - User Agent:     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/606.1 (KHTML, like Gecko) JavaFX/11 Safari/606.1
15:36:05.146 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - load html into WebEngine

Still getting it. Again, if I disable the listener for MAP_POINTER_MOVED, everything else works.

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-09 21:30
Okay, I think I've actually narrowed it down to two issues, one was with a java15 jdk built according to the javaFX dev notes, and I've resolved that.

The second is specific to my application, and my attempt at building a drag-and-drop for waypoint markers for a robot.

Since no drag is supported since we're using layers over webview, I am using "double click marker to pick it up, attach it to the cursor, and click again on the map to release it".

No click events are being processed.

The cursor is over the marker, which is following the cursor, but neither MARKER_CLICKED nor MAP_CLICKED are firing.

MOUSE_CLICKED does fire, so something is blockading the javascript events from propagating up, but it seems now that I've found an underlying compatibility issue, which is questionably reproducible, it's specifically related to when we "pick up" a marker.

Here is the code snippet for picking up a marker, as well as a boolean flag (simple setter method) to move it.

We are just creating and adding a marker at 0,0 to start the process, using the basic initialization of your demo map.

`map.addEventHandler(MarkerEvent.MARKER_DOUBLECLICKED, event -> {
			event.consume();
			draggingMarker = Marker.createProvided(Provided.RED).setPosition(event.getMarker().getPosition())
					.setVisible(true);// event.getMarker();
			map.addMarker(draggingMarker);
			System.out.println("Marker_doubleclicky");
		});
		map.addEventHandler(MapViewEvent.MAP_CLICKED, event -> {
			event.consume();
			if (draggingMarker != null) {
				draggingMarker.setPosition(event.getCoordinate()); // move marker along.
				map.removeMarker(testMarker);
				testMarker = draggingMarker;
				draggingMarker = null;
			}
			System.out.println("Clicky");
		});		
		map.addEventHandler(MouseEvent.MOUSE_CLICKED, event -> {			
			if (draggingMarker != null && !testFlag)
			{
				setTestFlag(true);				;
			}
			else if (draggingMarker != null && testFlag) {
				map.removeMarker(testMarker);
				testMarker = draggingMarker;
				draggingMarker = null;
			}
			System.out.println("Clicky");
			event.consume();
		});
		map.addEventHandler(MarkerEvent.MARKER_CLICKED, event -> {
			System.out.println("ClickyMarker");
			event.consume();
		});
		map.addEventHandler(MapViewEvent.MAP_POINTER_MOVED, event -> {
			if (draggingMarker != null)
				draggingMarker.setPosition(event.getCoordinate());
			event.consume();
		});`

**Comment by sothawo** [comment] 2021-03-09 21:32
as for formatting: for multiline code, you need to enclose in triple backticks

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-09 21:35
Thanks for the formatting fix, so this does just use markdown and the editor and app are still catching up?

It seems the scope of this issue is smaller than originally thought, but while a marker is "attached" to a cursor, click events are not thrown to it OR the map, despite the fact that we're not doing anything to cursor, only updating the position of the marker using its own API and a MAP_POINTER_MOVED.

I don't like this drag-and-drop workaround anyway, but now I like it even less?

**Comment by sothawo** [comment] 2021-03-09 22:31
Now with the code I see what you are trying to accomplish. You want to _select_ an existing marker by doubleclicking it which creates a new marker at this position (red one), _attaches_ it to the mouse cursor and follows the cursor. Then when clicking on the map again, the marker should kind of be dropped at the new location.

I will try to create a small example for that. Does the original marker have to stay at it's position until the red one is dropped? Or could the original marker be following the mouse after doubleclicking it?

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-09 23:39
Both cases cause the issue with the overlay. I've managed to create a very crazy workaround involving catching mouse_event and your events at the same time, as whenever I click, javafx does raise both.

Doesn't matter for the purposes of this test whether the original marker stays there and you drag a "ghost" around or if the original marker is being moved. Both fail in exactly the same way.

**Comment by sothawo** [comment] 2021-03-10 07:27
what I am trying to understand is what you want to achieve. Your problem might have to do with adding a visible marker in an event handler when it is as well used in a different handler. So I'd like to try to implement this dragging behaviour in a small example app and if it works, we could check for the difference. Therefore my question what behaviour you want to have.

**Comment by RbtsEvrwhr-Riley** [comment] 2021-03-10 14:09
The ultimate goal is very simple: any kind of user friendly means of moving active waypoints. drag and drop would make sense, as would a context menu command, to "pick up" a marker, attaching either it, or a "shadow' marker to the cursor to clearly show the user they are dragging a marker. My problems have been a mix of this issue, and the lack of access to screenX/Y position for mapview events.

**Comment by sothawo** [comment] 2021-03-10 22:16
I have written [a small application](https://github.com/sothawo/mapjfx-dragmarkers) that shows two variants of how dragging a marker can be implemented (using Java 11, tested on MacOS 10.15.7 and Win 10 20H2). The README.adoc in that repository explains how a drag is started and stopped/aborted.

**Comment by sothawo** [comment] 2021-04-01 18:47
Closing this issue as the provided linked examples shows two different ways to implement the dragging hint and no further activity on this issue.

**Closed by sothawo** 2021-04-01 18:47 UTC
